version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore ".\Serilog.Sinks.AzureWebJobsTraceWriter.sln"
build:
  project: .\Serilog.Sinks.AzureWebJobsTraceWriter.sln
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: zO/+Rey/GEVueni9Fp4eI4HLv4HxW+vb7McIAQEqOtjoj0DETsqUmV4AOWz1ZTOG
  skip_symbols: false
  artifact: /.*\.nupkg/